# Generated by Django 5.1 on 2024-11-08 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_remove_producto_fecha_vencimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='caracteristicas',
        ),
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.TextField(default='Sin especificar'),
            preserve_default=False,
        ),
    ]
